apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: testing-yaml-file
  description: this is a test file for the software catalog
  tags:
    - go
    - website
spec:
  type: service
  lifecycle: production
  owner: team-test
